Conference page project
Willian-Berrocal/Conference-page pull request #2
Opened 2022-10-20 15:42 UTC by Willian-Berrocal

- Setted up Linters
- Mobile version added
- Page deployed with GitHub Pages
- HTML files filled with content
- CSS styling done (for both mobile and desktop)
- Dynamic HTML done with JavaScript
- Menu buttons behavior done with JavaScript

2022-10-20 17:26 UTC, Abenezer-Tilahun requested changes
Hi @Willian-Berrocal  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct GitHub Flow.
✔️ Professional README 
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 17:26 UTC, Abenezer-Tilahun commented on main.js
> +}
- [x] Good job for creating HTML elements with the data from each object and attach the new element to a parent inside within the loop, But I recommend you to use a function that iterates through the speakers data on window load .

`window.onload = () => {
  speakersData.map(speaker => {
    
  })
}
`

2022-10-20 17:26 UTC, Abenezer-Tilahun commented on about.html
> +  </footer>
- [ ] As stated in the project requirement You should follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including: Colors, Kindly adjust background color of the footer section just like the design guidelines and In given design there is no partner section on about page for desktop screen size , please fix it.

Your About page Look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/197012563-6b030120-c53a-4ed6-ab47-3aa4c2cf7dab.PNG)

The Design guidelines About page look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/197012804-ff0f6679-7294-4e51-926d-03293a6f8029.PNG)

2022-10-20 17:26 UTC, Abenezer-Tilahun commented on index.html
> +      </div>
[OPTIONAL] I kindly suggest you to add the white border on hover for all the program articles just like the design guidelines.

Your all the program articles design look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/197013975-9d7399a9-d804-43fe-85c7-a19c69da2cb3.PNG)

The Design guidelines  program articles look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/197014213-62c1ad8b-76f7-4989-9391-8f1ea0d10c26.PNG)

2022-10-20 17:26 UTC, Abenezer-Tilahun commented on index.html
> +        </div>
- [ ] As stated in the project requirement the pages should look almost identical to the original design. So Kindly add transparent background image for all featured speakers just like the [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) and adjust background color for section.

The Design guidelines featured speakers section look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/197015338-98287e0c-0d19-421f-9f97-9df2c56d8bf0.PNG)

Your  featured speakers section look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/197015573-32883d72-e25a-4e1f-8e01-6ca8bbe70621.PNG)

[OPTIONAL] I kindly suggest  you  to add the line of text at the bottom to match the design, for mobile screen size.

The mobile screen size featured speakers section look likes this : 
<img width="382" alt="123" src="https://user-images.githubusercontent.com/93598189/197016130-371ec7d3-6c2e-4224-ab13-a1058978ff01.png">

2022-10-20 17:26 UTC, Abenezer-Tilahun commented on about.html
> +      </nav>
- [ ] It is redundant to have an `àbout` link on the about page. I kindly suggest you to replace this `about` page link with the `home` page link.
![Capture](https://user-images.githubusercontent.com/93598189/197016781-55cbc868-42b4-480c-b125-8aa52e075953.PNG)

2022-10-20 23:29 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @Willian-Berrocal, 

Great work on making the changes requested by the previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet, but don't worry you're almost there!! 😉

![image](https://media3.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif?cid=ecf05e4734q298svfm6dye74pbw2yeu64ps29whho9qaoirw&rid=giphy.gif&ct=g)

 ## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 23:29 UTC, mirouhml commented on about.html
>      </section>
- [ ] Please know that as the previous reviewer mentioned you should follow the design guidelines, the images of the past summits should have a kind of orange overlay, you can use the main color to do so:
  ![image](https://user-images.githubusercontent.com/20567503/197077880-058ebb59-d815-43ee-bd71-57e08c25a57e.png)
  Kindly adjust this then submit again!

2022-10-21 01:31 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @Willian-Berrocal , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Well done on implementing the requested change. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 14:09 UTC, merged